'use strict';
const KEY='florist-orders-v1', $=id=>document.getElementById(id), tz='Asia/Taipei';
let orders=load(), month=new Date(), selected='', editing=null;
const fields=['customer','customerPhone','source','product','quantity','unitPrice','deliveryFee','discount','productionDate','deliveryDate','slot','method','recipient','recipientPhone','address','status','payment','paymentMethod','paid','design','card','notes'];
function load(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v.filter(x=>x&&typeof x==='object'&&typeof x.id==='string'):[]}catch{return []}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(orders));return true}catch{alert('儲存失敗：瀏覽器空間不足。請先匯出備份。');return false}}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return new Intl.NumberFormat('zh-TW').format(Number(n)||0)}
function total(o){return Math.max(0,(Number(o.quantity)||0)*(Number(o.unitPrice)||0)+(Number(o.deliveryFee)||0)-(Number(o.discount)||0))}
function notify(s){$('notice').textContent=s;setTimeout(()=>{$('notice').textContent=''},4500)}
function filters(){let a=orders.filter(o=>{let q=$('search').value.trim().toLowerCase(),d=$('dateFilter').value,now=today(),future=new Date(now+'T12:00:00');future.setDate(future.getDate()+7);let end=future.getFullYear()+'-'+String(future.getMonth()+1).padStart(2,'0')+'-'+String(future.getDate()).padStart(2,'0');return (!q||[o.id,o.customer,o.customerPhone,o.recipient,o.recipientPhone,o.product,o.address].some(v=>String(v||'').toLowerCase().includes(q)))&&(!$('statusFilter').value||o.status===$('statusFilter').value)&&(!d||(d==='today'?o.deliveryDate===now:o.deliveryDate>=now&&o.deliveryDate<end))&&(!selected||o.deliveryDate===selected)});return a.sort((a,b)=>(a.deliveryDate+' '+a.slot).localeCompare(b.deliveryDate+' '+b.slot))}
function render(){let now=today(),active=orders.filter(o=>o.status!=='已取消'),up=active.filter(o=>o.deliveryDate===now),unpaid=active.filter(o=>o.payment!=='已付款'&&o.payment!=='已退款');$('summary').innerHTML=[['今天交付',up.length+' 筆'],['待製作',active.filter(o=>['待確認','待製作','製作中'].includes(o.status)).length+' 筆'],['未結清',unpaid.length+' 筆'],['今日訂單金額','NT$ '+money(up.reduce((n,o)=>n+total(o),0))]].map(([a,b])=>`<div class="metric">${a}<b>${b}</b></div>`).join('');renderCalendar();let a=filters();$('count').textContent=`${a.length} 筆${selected?' · '+selected:''}`;$('orders').innerHTML=a.length?a.map(o=>`<article class="order"><div class="order-top"><strong>${esc(o.product)} × ${esc(o.quantity)}</strong><span class="badge">${esc(o.status)}</span></div><small>${esc(o.deliveryDate)} · ${esc(o.slot)} · ${esc(o.method)} · ${esc(o.id)}</small><p>訂購：${esc(o.customer)} ${esc(o.customerPhone)}${o.method==='配送'?`<br>收件：${esc(o.recipient)} ${esc(o.recipientPhone)} · ${esc(o.address)}`:''}</p><p>NT$ ${money(total(o))} · ${esc(o.payment)}${o.paid?' · 已收 NT$ '+money(o.paid):''}${o.card?'<br>卡片：'+esc(o.card):''}${o.design?'<br>需求：'+esc(o.design):''}</p><div class="actions"><button data-action="edit" data-id="${esc(o.id)}">編輯</button><button data-action="google" data-id="${esc(o.id)}">加入 Google 日曆</button><button data-action="single" data-id="${esc(o.id)}">下載日曆</button><button class="danger" data-action="delete" data-id="${esc(o.id)}">刪除</button></div></article>`).join(''):'<p>沒有符合條件的訂單。</p>'}
function renderCalendar(){let y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=first.getDay();$('month').textContent=`${y} 年 ${m+1} 月`;let html=['日','一','二','三','四','五','六'].map(x=>`<div class="weekday">${x}</div>`).join('');for(let i=0;i<Math.ceil((offset+days)/7)*7;i++){let n=i-offset+1,date=new Date(y,m,n),key=date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0'),entries=orders.filter(o=>o.deliveryDate===key&&o.status!=='已取消');html+=`<button class="day ${n<1||n>days?'muted':''} ${key===today()?'today':''} ${key===selected?'selected':''}" data-date="${key}"><strong>${date.getDate()}</strong>${entries.slice(0,2).map(o=>`<span>${esc(o.product)} · ${esc(o.customer)}</span>`).join('')}${entries.length>2?`<span>＋${entries.length-2} 筆</span>`:''}</button>`}$('calendar').innerHTML=html}
function open(o){editing=o?.id||null;$('form').reset();$('formTitle').textContent=o?'編輯訂單':'新增訂單';let initial=o||{deliveryDate:today(),productionDate:today()};fields.forEach(k=>{let el=$('form').elements.namedItem(k);if(initial[k]!==undefined)el.value=initial[k]});preview();$('editor').showModal()}
function preview(){let f=$('form');$('totalPreview').textContent='訂單合計 NT$ '+money(total({quantity:f.quantity.value,unitPrice:f.unitPrice.value,deliveryFee:f.deliveryFee.value,discount:f.discount.value}))}
$('form').addEventListener('input',preview);$('form').addEventListener('submit',e=>{e.preventDefault();let f=e.currentTarget,v=Object.fromEntries(fields.map(k=>[k,f.elements.namedItem(k).value.trim()]));for(let k of ['quantity','unitPrice','deliveryFee','discount','paid'])v[k]=Number(v[k])||0;if(v.method==='配送'&&(!v.recipient||!v.recipientPhone||!v.address)){alert('配送訂單請填收件人、電話與地址。');return}if(v.productionDate&&v.productionDate>v.deliveryDate){alert('製作日期不能晚於交付日期。');return}if(v.discount>v.quantity*v.unitPrice+v.deliveryFee){alert('折扣不能大於訂單金額。');return}if(v.paid>total(v)){alert('已收金額不能大於訂單合計。');return}let old=orders.find(x=>x.id===editing);let record={...old,...v,id:old?.id||'FL-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};orders=old?orders.map(x=>x.id===editing?record:x):[...orders,record];if(save()){$('editor').close();selected='';render();notify('訂單已儲存')}});
$('new').onclick=()=>open();$('cancel').onclick=()=>$('editor').close();['search','statusFilter','dateFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{selected='';render()}));$('prev').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);selected='';render()};$('next').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);selected='';render()};$('calendar').onclick=e=>{let d=e.target.closest('[data-date]');if(d){selected=selected===d.dataset.date?'':d.dataset.date;render()}};
$('orders').onclick=e=>{let b=e.target.closest('[data-action]');if(!b)return;let o=orders.find(x=>x.id===b.dataset.id);if(!o)return;switch(b.dataset.action){case 'edit':open(o);break;case 'delete':if(confirm(`確定永久刪除 ${o.id}？請先匯出備份。`)){orders=orders.filter(x=>x.id!==o.id);save();render()}break;case 'single':downloadIcs([o]);break;case 'google':window.open(googleUrl(o),'_blank','noopener,noreferrer')}};
function download(data,name,type){let url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=()=>download(JSON.stringify({version:1,exportedAt:new Date().toISOString(),orders},null,2),'花店訂單備份-'+today()+'.json','application/json');
$('import').onchange=async e=>{let file=e.target.files[0];if(!file)return;try{if(file.size>10_000_000)throw Error('檔案過大（上限 10 MB）');let raw=JSON.parse(await file.text()),a=raw.orders;if(!Array.isArray(a)||a.some(x=>!x||typeof x.id!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(x.deliveryDate||'')))throw Error('備份格式或日期不正確');if(!confirm(`將用備份中 ${a.length} 筆訂單取代目前 ${orders.length} 筆訂單，確定嗎？`))return;let previous=orders;orders=a.map(o=>Object.fromEntries(Object.entries(o).filter(([k])=>[...fields,'id','createdAt','updatedAt'].includes(k))));if(!save())orders=previous;else{selected='';render();notify('備份已匯入')}}catch(err){alert('匯入失敗：'+err.message)}finally{e.target.value=''}};
function startEnd(o){let mapping={'上午 09:00–12:00':['09','12'],'下午 12:00–17:00':['12','17'],'晚上 17:00–21:00':['17','21'],'指定時間（見備註）':['09','10']},[s,e]=mapping[o.slot]||['09','10'],d=o.deliveryDate.replaceAll('-','');return[d+'T'+s+'0000',d+'T'+e+'0000']}
function icsEscape(s){return String(s??'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function downloadIcs(list){let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Florist Orders//ZH-TW','CALSCALE:GREGORIAN','X-WR-TIMEZONE:Asia/Taipei'];list.filter(o=>o.deliveryDate&&o.status!=='已取消').forEach(o=>{let [s,e]=startEnd(o),description=`訂單 ${o.id}\n狀態 ${o.status}\n品項 ${o.product} × ${o.quantity}\n訂購 ${o.customer} ${o.customerPhone}\n收件 ${o.recipient||''} ${o.recipientPhone||''}\n卡片 ${o.card||''}\n備註 ${o.notes||''}`;lines.push('BEGIN:VEVENT',`UID:${o.id}@florist-orders.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=Asia/Taipei:${s}`,`DTEND;TZID=Asia/Taipei:${e}`,`SUMMARY:${icsEscape(o.product+' × '+o.quantity+'｜'+o.customer)}`,`DESCRIPTION:${icsEscape(description)}`,`LOCATION:${icsEscape(o.method==='配送'?o.address:'店取')}`,'END:VEVENT')});lines.push('END:VCALENDAR');download(lines.join('\r\n')+'\r\n',list.length===1?list[0].id+'.ics':'花店訂單日曆-'+today()+'.ics','text/calendar;charset=utf-8')}
function googleUrl(o){let [s,e]=startEnd(o),p=new URLSearchParams({action:'TEMPLATE',text:o.product+' × '+o.quantity+'｜'+o.customer,dates:s+'/'+e,ctz:tz,details:`訂單 ${o.id}\n訂購 ${o.customer} ${o.customerPhone}\n收件 ${o.recipient||''} ${o.recipientPhone||''}\n卡片 ${o.card||''}\n備註 ${o.notes||''}`,location:o.method==='配送'?o.address:'店取'});return 'https://calendar.google.com/calendar/render?'+p.toString()}
$('ics').onclick=()=>downloadIcs(orders);render();
